# These are supported funding model platforms

# github: tomasmotahq
instagram: goncaloo__teixeiraa
# custom: https.//lnk.to/tomasmota
# ko_fi: tomasmota
# buy_me_a_coffee: # tomasmota
# thanks_dev: # tomasmotahq
